version: '3.9'

services:
  db:
    image: library/postgres:13.1-alpine
    volumes:
    - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  webapp:
    build: .
    command: bash -c "python /survey_test/manage.py makemigrations &&
                      python /survey_test/manage.py migrate &&
                      python /survey_test/manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/survey_test
    ports:
    - 8000:8000
    depends_on:
      - db

volumes:
  db_data: